#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_LOCATION_NAME_LENGTH 128
#define MAX_URL_LENGTH 256
#define MAX_LOCATIONS 1024

#define MIN_SECONDS_BETWEEN_CALLS 5

#define API_DATA_RELEASE_ITERVAL_SECONDS 900

#endif /* CONSTANTS_H */
